### ISSUE TITLE
Rework the chapters.

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#9]
* The chapters could be more generalized by removing the protocols and putting them in their own *chapter per protocol* or putting them in the *Appendix*.

* The chapters need to be renamed to include more general terms like:

```yaml
chapter_3: 
  filename: "03-molecular-isolation.Rmd"
  text: "Molecular: Isolation"
chapter_4:
  filename: "04-molecular-pcr.Rmd"
  text: "Molecular: PCR"
```
